### ISSUE TITLE
The game crashed whilst quartz failed to startup Error: java.lang.ExceptionInInitializerError: null Exit Code: -1

### ISSUE THREAD

**Issue by Tikin573** [BiggerSeries/Quartz#2] opened 2022-01-13 04:18 UTC
https://pastebin.com/rHJ65zyU

I have the mods from All The Mods 7, including phosphophyllite-1.18.1-0.6.0-beta.jar

**Comment by gizmocodes** [comment] 2022-01-13 04:43
This appears to be a duplicate of #1, check elsewhere in your log file and you should be able to find the mod that is missing dependencies/erroring out. The message from Quartz is a red herring; this should be fixed in the next update.

**Closed as completed by gizmocodes** 2022-01-13 04:43 UTC

**Comment by Tikin573** [comment] 2022-01-13 04:53
I tried doing it manually as ATM7 wasn't updated yet and I didn't feel like waiting, but they just updated All The Mods 7 an hour ago. They removed a mod and updated all the others and it works, of course.

Thank you for replying and I hope that I didn't waste your time. or at least not too much. Thanks again!

**Comment by gizmocodes** [comment] 2022-01-13 04:55
Don't worry about it, it's no bother. I guess I should have specified the next update of Quartz rather than ATM7, but whenever the Quartz release comes out then the update of ATM7 after that should include it. Thanks for the report!

**Comment by Tikin573** [comment] 2022-01-13 05:13
I guess I should mention that in the log it said that libx was missing, but I had that in the list. Not sure what was going on with that.
